<a href="https://colab.research.google.com/github/Linda8a/ANum/blob/tarefas-em-colab/Tarefa2elimina%C3%A7aogaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercises
1. Solve step by step a random 4×4 linear system (use the first 4 digits of your cpf for the seed), describing each step of the GaussElimin and GaussRetro algorithm. Check the answer by calculating the residue.

In [1]:
import numpy as np

#os primeiros 4 dígitos do CPF como seed: 0140
np.random.seed(140)

# Criar matriz aleatoria 4x4
A = np.random.rand(4, 4)
# Criar un vetor aleatorio 4x1
B = np.random.rand(4, 1)

print(f'A:{A}')
print(f'B: {B}')


A:[[0.74790552 0.10873232 0.00098478 0.29656331]
 [0.0019685  0.32063765 0.09247783 0.59127811]
 [0.19194663 0.91172461 0.88880116 0.48760579]
 [0.27527877 0.10268944 0.09207659 0.85574278]]
B: [[0.7547835 ]
 [0.36064195]
 [0.03971011]
 [0.88210098]]


In [2]:
# Función para eliminación gaussiana
def gauss(a, b):
    n = len(b)
    a = a.copy()  # preserva a entrada
    b = b.copy()

    for k in range(0, n - 1):  # linha pivo
        for i in range(k + 1, n):  # recorre las filas / columna a eliminar
            m = a[i][k] / a[k][k]  # operación entre líneas

            a[i, k + 1:n] = a[i, k + 1:n] - m * a[k, k + 1:n]  # actualiza la línea i (vectorización)
            a[i, k] = 0  # que es 0 por definición
            b[i] = b[i] - m * b[k]  # actualiza el elemento de la columna

    return np.hstack([a, b])  # devuelve la matriz aumentada

gauss(A,B)


array([[ 7.47905516e-01,  1.08732320e-01,  9.84776414e-04,
         2.96563309e-01,  7.54783505e-01],
       [ 0.00000000e+00,  3.20351467e-01,  9.24752387e-02,
         5.90497549e-01,  3.58655348e-01],
       [ 0.00000000e+00,  0.00000000e+00,  6.33418114e-01,
        -1.21763191e+00, -1.14349739e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.72599965e-01,  6.67040070e-01]])

In [3]:
# Función retro-sustitución
def GaussRetro(a, b):
    a = a.copy()
    b = b.copy()
    n = len(b)
    x = np.zeros(n)   #cria vetor de tamanho n
    x[n-1] = (b[n-1] / a[n-1, n-1]).item()   #calcula a incógnita no último elemento
    for k in range(n-2, -1, -1):
        x[k] = ((b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]).item()   #item extrae el valor como escalar y no como array


    return np.transpose([x])  # Devolve vetor de soluções em forma de vetor coluna

In [4]:
# Chamar função para fazer eliminação da matriz aumentada
M1 = gauss(A, B)
M1

array([[ 7.47905516e-01,  1.08732320e-01,  9.84776414e-04,
         2.96563309e-01,  7.54783505e-01],
       [ 0.00000000e+00,  3.20351467e-01,  9.24752387e-02,
         5.90497549e-01,  3.58655348e-01],
       [ 0.00000000e+00,  0.00000000e+00,  6.33418114e-01,
        -1.21763191e+00, -1.14349739e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.72599965e-01,  6.67040070e-01]])

In [5]:
# uma vez que temos a matriz escalonada, separar a matriz A das incógnitas, e B
A1 = M1[:, 0:4]
B1 = M1[:, 4]

# chamar a função de calcular as incógnitas por retrosubstituição
x1 = GaussRetro(A1, B1)
print(f'X= {x1}')

# Calcular residuo
residuo = A @ x1 - B
print(f'\n Residuos:\n {residuo}')

X= [[ 0.72953022]
 [-0.42983369]
 [-0.14560657]
 [ 0.86337057]]

 Residuos:
 [[-1.11022302e-16]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


2. Solve a random system 500×500 using the GaussSolve algorithm (do not show the result). Check the correctness of the result by calculating the residue norm and compare the required CPU time. Repeat the procedure using numpy's solver.

In [6]:
#criar matriz 500x500
import numpy as np
np.random.seed(123)
N=500
A=np.random.rand(N,N)
B=np.random.rand(N,1)



In [7]:
def GaussSolve(a,b):
  n=len(a)
  a=a.copy() #preserva a entrada
  b=b.copy()
  x=np.zeros(n)
  for k in range(0,n-1): #linha pivot
    for i in range(k+1,n): #percorre linhas / coluna a ser eliminada
      m=a[i][k]/a[k][k]  #operaçaõ entre linhas

      a[i,k+1:n]=a[i,k+1:n]-m*a[k,k+1:n] #atualiza elem da linha i (vetorização)
      a[i,k]=0   #que é zero por definição
      b[i]=b[i]-m*b[k]   #atualiza elem da coluna
    x[n-1]=(b[n-1]/a[n-1,n-1]).item()
  for k in range(n-2,-1,-1):
    x[k]=((b[k]-np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]).item()

  return np.transpose([x])


In [8]:
x=GaussSolve(A,B) #obtendo a solução e mostrando apenas o residuo

residuo = np.linalg.norm(A @ x - B, ord=np.inf)
residuo


np.float64(1.2681411476478388e-11)

In [9]:
# mostrar tempo de resolução do algoritmo
%%timeit
GaussSolve(A, B)

1.44 s ± 896 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
x_numpy=np.linalg.solve(A,B) #obtendo a solução com o solucionador de nympy e mostrando o residuo

residuo_numpy=np.linalg.norm(A @ x_numpy - B, ord=np.inf)
residuo_numpy

np.float64(7.582823258189819e-14)

In [11]:
# mostrar o tempo do solucionador de numpy
%%timeit
x_numpy = np.linalg.solve(A, B)


5.67 ms ± 188 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


3. The condition number of a matrix A, denoted by κ(A), measures the sensitivity of the solution of a linear system Ax=b to such small perturbations in the matrix A or in the vector b. It is defined as:
κ(A)=∥A∥⋅∥A−1∥,
where ∥A∥ is the norm of the matrix (usually the 2-norm). A high condition number indicates that the system is ill-conditioned, i.e., small changes in the data can cause large variations in the solution. An example of an ill-conditioned matrix is ​​the Hilbert matrix Hn of order n, defined by
Hij=1i+j+1,i,j=0,1,…,n.

In [12]:
# função para criar a matriz de Hilbert
def hilb(n):
    return np.array([[1/(i+j+1) for i in range(n)] for j in range(n)])
    return np.array([[1/(i+j+1) for i in range(n)] for j in range(n)])

(i) Solve the linear system  HX=B , where  H  is the Hilbert matrix  H(30) ,  30×30  and B is a column matrix with all elements having the value 1. Use the Gaussian elimination algorithm developed earlier to solve the system. Calculate the residual in both cases.

In [13]:
H = hilb(30) #matriz Hilbert 30x30
B = np.ones([30,1]) #criar matriz B com elementos = 1

# usar algoritmo de eliminação gaussiana e mostrando o residuo
X = GaussSolve(H, B)
residuo_gauss = np.linalg.norm(H @ X - B, ord=np.inf)
print(f'Residuo: {residuo_gauss}')



Residuo: 2.7008354663848877e-08


In [14]:
# resolvendo com solucionador de numpy e mostrando o residuo
x_numpy = np.linalg.solve(H, B)
residuo_numpy = np.linalg.norm(H @ x_numpy - B, ord=np.inf)
print(f'Residuo solucionador de numpy: {residuo_numpy}')

Residuo solucionador de numpy: 1.4062970876693726e-07


(ii) Compare the condition number of  H  with that of a random matrix  30×30 . Use the command

In [15]:
# perturbação: κ(A)=∥A∥⋅∥A−1∥, where ∥A∥ is the norm of the matrix (usually the 2-norm)

# criar matriz aleatoria 30x30
A_random = np.random.rand(30, 30)

# calcular sua inversa
inv_random = np.linalg.inv(A_random)

# calcular o número de condição da inversa
cond_inv_random = np.linalg.cond(inv_random)

#calcular num de condiçao da matriz aleatória
cond_random = np.linalg.cond(A_random,2) * cond_inv_random


In [16]:
inv=np.linalg.inv(H) #inversa de H

#calcular num de cond da inversa de H
cond_inv = np.linalg.norm(inv, 2)

# Calcular num de cond de H
cond_H = np.linalg.norm(H, 2) * cond_inv


In [17]:
print(f"Número de condição de H(30): {cond_H}")
print(f"Núm. de condição de matriz : {cond_random}")

Número de condição de H(30): 3.4953017711786173e+18
Núm. de condição de matriz : 215442.76116776874


In [18]:
#copiar matriz H
H_copia = H.copy()

# modificar/perturbar elemento a00
H_copia[0, 0] += 1e-15

# resolver para X perturbada
X_perturbed = np.linalg.solve(H_copia, B)

# calcular diferença entre as soluçoes
solution_diff = np.linalg.norm(X - X_perturbed, ord=np.inf)

print(f"Diferença: {solution_diff}")


Diferença: 9757690384.077839


4. Study system instability with Hilbert matrices  n×n . For example, vary the value of a coefficient of B slightly, or add a small term to the matrix H. Use the solver in Numpy.

In [19]:
#vamos variar o coeficiente a5 da matriz B
B_copia=B.copy()

B_copia[5] -= 1e-5

#resolver o sistema com esa pequena variação
X2 = np.linalg.solve(H, B_copia)
residuo_copia = np.linalg.norm(H @ X2 - B_copia, ord=np.inf)
print(f'Residuo: {residuo_copia}')

#comparando com residuo sem perturbação
print(f'Residuo sem perturbação: {residuo_numpy}')

Residuo: 6.712973117828369e-06
Residuo sem perturbação: 1.4062970876693726e-07


5. Define a system  GX=B ,  n×n , with  G=[gij]  and  gij=1/(1+i+2j) . Check if such a system is also unstable. Vary  n . Use the solver in Numpy.

In [87]:
import numpy as np

# vamos variar os valores de n manualmente
n1 = int(input('Valor de n1: '))
n2 = int(input('Valor de n2: '))
n3 = int(input('Valor de n3: '))
n = [n1, n2, n3]


Valor de n1: 10
Valor de n2: 100
Valor de n3: 500


In [88]:
#criar matriz G
def m5(n):
    return np.array([[1/(i+2*j+1) for i in range(n)] for j in range(n)])

#função para criar matriz B com elementos=1
def mB(n):
    return np.ones([n,1])


#resolver o sistema com solucionador de numpy e achar o residuo
def resolver_sistema(G, B):
    X = np.linalg.solve(G, B)
    residuo = np.linalg.norm(G @ X - B, ord=np.inf)
    return X, residuo

def comprobar_inestabilidad(G, B):
    # Número de condición
    cond_G = np.linalg.cond(G)
    print(f'Número de condición de G: {cond_G}')


In [89]:
#chamar as funções para os diferntes valores de n
for i in n:
    G = m5(i)
    B= mB(i)
    X, residuo = resolver_sistema(G, B)
    print(f'n = {i}: residuo = {residuo}')    #com variações no n não parece ter muita inestabilidade, podemos perturbar o sistema para ver se continua da mesma forma (pendente)

n = 10: residuo = 4.190951585769653e-09
n = 100: residuo = 3.814697265625e-06
n = 500: residuo = 7.2479248046875e-05
